# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: xoxb-992869852182-2382134462402-gjYGMHXWOfC74MOQFfxcUvRE
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: build_status
        status: STARTING
        color: warning
        
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest *.py
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: xapp-1-A02BLMW9R7T-2388324018532-87e53aba8efa6504f8fca98cd399a2cd119652c48c2cafba87c59eb3921ce006
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: app-alerts
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: xapp-1-A02BLMW9R7T-2388324018532-87e53aba8efa6504f8fca98cd399a2cd119652c48c2cafba87c59eb3921ce006
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: app-alerts
        status: FAILED
        color: danger
